# Generated by Django 5.1.3 on 2024-11-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=200)),
                ("id_discord", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text_resume", models.TextField()),
                ("text_complete", models.TextField()),
                ("messages", models.ManyToManyField(to="polls.message")),
                ("users", models.ManyToManyField(to="polls.user")),
            ],
        ),
    ]
